# basic
backend: 'tf_keras'
gpus:
    - 0
    - 1
save_dir: 'tmp'

# dataset
dataset: 'fashion_mnist'
test_data:
validation_data:

# network
network: 'fcn'
in_heights: 
    - 28
in_widths:
    - 28
in_channels:
    - 1
classes:
    - 10
weights:
dropout_keep_prob: 1.0
l2_lambda: 0

# optimization
optimizer: 'adam'
learnig_rate: 0.001

# training
batch_size: 256
num_epochs: 100
