# basic
backend: 'tf_keras'
gpus:
    - 0
    - 1
save_dir: 'tmp'

# dataset
dataset: '/dataset/stanford-dogs-dataset/cropped_dataset/train'
test_data: '/dataset/stanford-dogs-dataset/cropped_dataset/test'
validation_data: '/dataset/stanford-dogs-dataset/cropped_dataset/validation'

# network
network: 'fcn'
in_heights: 
    - 224
in_widths:
    - 224
in_channels:
    - 3
classes:
    - 120
weights:
dropout_keep_prob: 1.0
l2_lambda: 0.003

# optimization
optimizer: 'rmsprop'
learning_rate: 0.0001
learning_rate_decay: 0.98

# training
batch_size: 192
num_epochs: 200
